language: python
python:
    - 2.7.8
    - 2.7
    - 3.5
    - 3.6
    - nightly

# command to install dependencies
install: 
     - python setup.py install
     
# command to run tests
script: 
    pytest
sudo: false

matrix:
    fast_finish: true
    include:
        env: LINT_CHECK
        python: "2.7"
        install: pip install flake8
        script: flake8
